# Generated by Django 5.0.1 on 2024-02-10 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='borrowhistory',
            name='book',
        ),
        migrations.RemoveField(
            model_name='borrowhistory',
            name='borrower',
        ),
        migrations.DeleteModel(
            name='Book',
        ),
        migrations.DeleteModel(
            name='BorrowHistory',
        ),
    ]
